### ISSUE TITLE
Libgridxc compilation.

### ISSUE THREAD

**Issue by disi98** [siesta-project/gridxc-docs#1]
when trying to compile libgridxc with libxc for siesta psml i got the following error
![Screenshot from 2020-09-24 12-05-33](https://user-images.githubusercontent.com/67419107/94124925-55e9fb80-fe5e-11ea-8ee0-fbddc2a9056d.png)
''
/home/disi/Progrms/sisestaPSML/lib/libgridxc-0.8.5/src/ldaxc.F90:98:8:

   98 |     use xc_f90_types_m
      |        1
Fatal Error: Cannot open module file ‘xc_f90_types_m.mod’ for reading at (1): No such file or directory
compilation terminated.
make: *** [/home/disi/Progrms/sisestaPSML/lib/libgridxc-0.8.5/Gfortran/fortran.mk:34: ldaxc.o] Error 1
''
What shall I do now,,

**Comment by zerothi** [comment]
Could you please try the latest release here: https://gitlab.com/siesta-project/libraries/libgridxc/uploads/e6e4ec1e3ec648a45b3613e724c7be04/libgridxc-0.9.6.tar.gz

**Comment by disi98** [comment]
It is still displaying the same error,,,

I think the error comes from the ldaxc.F90 file because it contains *"*
*use* *xc_f90_types_m"* code.  But I don't know how to fix it!!!
Any further help please!!

**Comment by zerothi** [comment]
Well, the error message is pretty clear, it misses the libxc module files. So you should ensure you have enabled the correct flags for linking against libxc, from what you show we cannot help any further since the fault is somewhere on your side...

Could you please clearly state all steps you did (including how you installed libxc).

**Comment by disi98** [comment]
After downloading the package, I moved it to
*~/Documents/lib.   ...*the path where am to install all my librario.
Then I used the following commands for installation:

*$  cd  ~/Documents/lib/*
*$  tar -zxvf  libxc-5.0.0.tar.gz*
*$  cd **libxc-5.0.0*
*$  mkdiri Gfortran*
*$  cd Gfortran*
*$  /configure ..prefix=/home/disi/Documents/lib/Gfortran*
*$  make -j4*
*$  make install*

The compilation for Libxc runs successfully.
But when I compile libgridxc with libxc the when I get the error...
I use the following command to compile libgridxc:

*$  tar -zxvf libgridxc-0.9.6.tar.gz*
*$  cd libgridxc-0.9.6*
*$  mkdiri Gfortran*
*$  cd Gffortran.mkortran*
*$  cp ../extra/fortran.mk <http://fortran.mk> .*
*$  vi fortran.mk <http://fortran.mk>*
*$  sh ../src/config.sh*
*$  make clean*
*$  WITH_LIBXC=1  WITH_MPI=  PREFIX=/home/disi/Documents/lib/Gfortran sh
built.sh*

In the fortran.mk file I changed the line to
*LIBXC_ROOT=/home/disi/Documents/lib/Gfortran*
as shown in the image.

**Comment by albgar** [comment]
Just a warning: libxc V5 is too new. We have only checked libgridxc up to V4.

**Comment by disi98** [comment]
Libgridxc 4.3 has worked
Thank you for your help!!!
